[package]
name = "serde_urlencoded"
version = "0.7.1" # bump in documentation link and in README on update
authors = ["Anthony Ramine <n.oxyde@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/nox/serde_urlencoded"
documentation = "https://docs.rs/serde_urlencoded/0.7.1/serde_urlencoded/"
description = "`x-www-form-urlencoded` meets Serde"
categories = ["encoding", "web-programming"]
keywords = ["serde", "serialization", "urlencoded"]
exclude = ["/.travis.yml", "/bors.toml"]
edition = "2018"

[badges]
travis-ci = {repository = "nox/serde_urlencoded"}

[lib]
test = false

[dependencies]
form_urlencoded = "1"
itoa = "1"
ryu = "1"
serde = "1.0.69"

[dev-dependencies]
serde_derive = "1"
